### ISSUE TITLE
I'm install the package Colopicker in ST3, when I press ctrl+shift+c:

### ISSUE THREAD

**Issue by shilovk** [weslly/ColorPicker#51]
```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 549, in run_
    return self.run(edit)
  File "sublimecp in C:\Users\konst\AppData\Roaming\Sublime Text 3\Installed Packages\ColorPicker.sublime-package", line 172, in run
  File "sublimecp in C:\Users\konst\AppData\Roaming\Sublime Text 3\Installed Packages\ColorPicker.sublime-package", line 240, in pick_win
  File "X/ctypes/__init__.py", line 431, in LoadLibrary
  File "X/ctypes/__init__.py", line 353, in __init__
OSError: [WinError 193] %1 не является приложением Win32
```

How to fix it?

**Comment by weslly** [comment]
Fixed in the latest releases

**Comment by anreyado** [comment]
Error still occurr. Windows XP, Sublime Text3 3083, Colopicker v1.13.2 installed with Package Control.
```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 556, in run_
    return self.run(edit)
  File "C:\Documents and Settings\Андрей\Application Data\Sublime Text 3\Packages\ColorPicker\sublimecp.py", line 365, in run
    color = cp.pick(self.view.window(), selected)
  File "C:\Documents and Settings\Андрей\Application Data\Sublime Text 3\Packages\ColorPicker\sublimecp.py", line 316, in pick
    proc = subprocess.Popen(args, stdout=subprocess.PIPE)
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1118, in _execute_child
OSError: [WinError 193] %1 не является приложением Win32ut=subprocess.PIPE)
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1118, in _execute_child
OSError: [WinError 193] %1 не является приложением Win32
```
