### ISSUE TITLE
installation not working

### ISSUE THREAD

**Issue by tjvoll** [weslly/ColorPicker#65]
I'm trying to install this through package control and there are no errors yet the plugin does not seem to be working.  There are no package settings, no new key bindings, etc... 

The only file that seems relevant to colorPicker is the linux_colorpicker.py file in Packages/User/ColorPicker/bin

I've tried with both SL2 and SL3 on scientific linux 6.4

Am I out of luck?

**Comment by weslly** [comment]
Can you try again with the latest release?

**Comment by tjvoll** [comment]
hey there,

I tried installing again and am getting this error now,
Traceback (most recent call last):
  File
"/home/personal_folders/t.voll/Software/sublime_text_3/sublime_plugin.py",
line 549, in run_
    return self.run(edit)
  File
"/home/personal_folders/t.voll/.config/sublime-text-3/Packages/ColorPicker/sublimecp.py",
line 376, in run
    self.view.replace(edit, region, '#' + color)
TypeError: Can't convert 'bytes' object to str implicitly

**Comment by facelessuser** [comment]
https://github.com/weslly/ColorPicker/commit/cc1e670b173792a07d26308128902715adf081ef should fix that error.  The error should only occur when the user dismisses the color picker without accepting the color.  At least that is the case the commit fixes.  Colors should be decoded to normal strings otherwise.

**Comment by tjvoll** [comment]
That's odd.  The color picker UI wasn't launching for me then.  That error
was immediately returned after running the command.  Still happens in
sublime3.  In sublime2 it just returns a #.  Must be something up with kde.

**Comment by facelessuser** [comment]
Ahh, it must be that the linux script is some how not playing nice with your distro then.  I assumed you were talking about the just getting the error.  The error I fixed didn't actually affect functionality as it only occurred when nothing was to be done anyways.

I think your problem is more likely with the linux script used to show the colorpicker https://github.com/weslly/ColorPicker/blob/master/lib/linux_colorpicker.py.  I haven't looked into that specifically, but I imagine with so many different linux distros, it would be difficult to easily provide a script that works on every version of linux in every distro without failing on some.

**Comment by tjvoll** [comment]
oh, bummer!  That's too bad, but I understand.

**Comment by facelessuser** [comment]
I would try directly running that linux colorpicker script and reporting on what kinds of errors you may be seeing.  Maybe it something easy to figure out.

**Comment by tjvoll** [comment]
ahh, thanks for the suggestion.  It appears my distro does not include
gi.repository.  When I get a minute I'll install that and try again.

**Comment by facelessuser** [comment]
Cool, just let us know if you were able to resolve the issue by installing the repo.  This will enable us to give the same advise to others with similar issues.

**Comment by tjvoll** [comment]
will do!

**Comment by seanjohnson08** [comment]
Fixed in https://github.com/weslly/ColorPicker/pull/71
